In [6]:
import pandas as pd
train_df = pd.read_csv('train.csv')
print(train_df.head())
print(train_df.info())
print(train_df.describe(include='all')) # include='all' zeigt auch Infos zu nicht-numerischen Spalten
print(train_df.isnull().sum())

# Finde den häufigsten Hafen (den Modus)
embarked_mode = train_df['Embarked'].mode()[0]
print(f"Der häufigste Einschiffungshafen ist: {embarked_mode}")

# Fülle die fehlenden Werte in der 'Embarked'-Spalte mit diesem Wert
# inplace=True bedeutet, dass die Änderung direkt im DataFrame vorgenommen wird
train_df['Embarked'].fillna(embarked_mode, inplace=True)

# Überprüfung: Jetzt sollten keine fehlenden Werte mehr in 'Embarked' sein
print(f"Fehlende Werte in 'Embarked' nach dem Füllen: {train_df['Embarked'].isnull().sum()}")

# Calculate the median age
age_median = train_df['Age'].median()
print(f"Das Median-Alter beträgt: {age_median}")

# Fill the missing 'Age' values with the median
train_df['Age'] = train_df['Age'].fillna(age_median)

# Verify that there are no more missing 'Age' values
print(f"Fehlende Werte in 'Age' nach dem Füllen: {train_df['Age'].isnull().sum()}")

# Drop the 'Cabin' column from the DataFrame
train_df.drop('Cabin', axis=1, inplace=True)

print("Die 'Cabin'-Spalte wurde entfernt.")

# Erstelle ein Mapping: 'male' wird zu 0, 'female' wird zu 1
sex_mapping = {'male': 0, 'female': 1}
train_df['Sex'] = train_df['Sex'].map(sex_mapping)

print("Die 'Sex'-Spalte wurde in numerische Werte umgewandelt.")

# Führe One-Hot Encoding für die 'Embarked'-Spalte durch
# Dies erstellt neue Spalten: Embarked_C, Embarked_Q, Embarked_S
embarked_dummies = pd.get_dummies(train_df['Embarked'], prefix='Embarked')

# Füge die neuen Spalten zu unserem DataFrame hinzu
train_df = pd.concat([train_df, embarked_dummies], axis=1)

# Entferne die ursprüngliche 'Embarked'-Textspalte, da wir sie nicht mehr brauchen
train_df.drop('Embarked', axis=1, inplace=True)

print("Die 'Embarked'-Spalte wurde durch One-Hot Encoding ersetzt.")

# Entferne die für das Training nicht benötigten Spalten
train_df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

print("Die Spalten 'PassengerId', 'Name' und 'Ticket' wurden entfernt.")

# Zeige die ersten 5 Zeilen des final vorbereiteten DataFrames an
print("\nFinal vorbereiteter Datensatz (erste 5 Zeilen):")
print(train_df.head())

# Überprüfe die Datentypen aller verbleibenden Spalten
print("\nDatentypen der finalen Spalten:")
train_df.info()

# Unsere Zielvariable y ist die 'Survived'-Spalte
y = train_df['Survived']

# Unsere Merkmale X sind alle Spalten außer 'Survived'
X = train_df.drop('Survived', axis=1)

# Überprüfen wir kurz die Dimensionen
print(f"Form der Merkmale (X): {X.shape}")
print(f"Form der Zielvariable (y): {y.shape}")

from sklearn.model_selection import train_test_split

# Teile die Daten auf. random_state=42 sorgt dafür, dass die Aufteilung immer gleich ist.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Größe des Trainingssets: {len(X_train)} Passagiere")
print(f"Größe des Testsets: {len(X_test)} Passagiere")

from sklearn.linear_model import LogisticRegression

# 1. Initialisiere das Modell
# Wir setzen max_iter=1000, um sicherzustellen, dass das Modell genügend Zeit zum Lernen hat
model = LogisticRegression(max_iter=1000)

# 2. Trainiere das Modell mit unseren Trainingsdaten
model.fit(X_train, y_train)

print("Modell (Logistische Regression) wurde erfolgreich trainiert!")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Mache Vorhersagen auf dem Testset
y_pred = model.predict(X_test)

# 1. Berechne die Genauigkeit (Accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(f"Genauigkeit des Modells auf dem Testset: {accuracy * 100:.2f}%")

# 2. Zeige den detaillierten Klassifikationsbericht
print("\nKlassifikationsbericht:")
print(classification_report(y_test, y_pred))

# 3. Zeige die Konfusionsmatrix
# [[True Negative, False Positive]
#  [False Negative, True Positive]]
print("\nKonfusionsmatrix:")
print(confusion_matrix(y_test, y_pred))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
        PassengerId    Survived      Pclass                 Name   Sex  \
count    891.000000  891.000000  891.000000                  891   891
unique          NaN         NaN         NaN                  891     2
top             NaN         NaN         NaN  Dooley, Mr. Patrick  male
freq            NaN         NaN         NaN                    1   577
mean     446.000000    0.383838    2.308642                  NaN   NaN
std      257.353842    0.486592    0.836071                  NaN   NaN
min        1.000000    0.000000    1.000000                  NaN   NaN
25%      223.500000    0.000000    2.000000                  NaN   NaN
50%      446.000000    0.000000    3.000000                  NaN   NaN
75%      668.500000    1.000000    3.000000                  NaN   NaN
max      891.000000    1.000000    3.000000                  NaN   NaN

               Age       SibSp       Parch  Ticket        Fare Cabin Embarked
count   714.000000  891.000000  891.000000     891  891.000000   204      889
unique         NaN         NaN         NaN     681         NaN   147        3
top            NaN         NaN         NaN  347082         NaN    G6        S
freq           NaN         NaN         NaN       7         NaN     4      644
mean     29.699118    0.523008    0.381594     NaN   32.204208   NaN      NaN
std      14.526497    1.102743    0.806057     NaN   49.693429   NaN      NaN
min       0.420000    0.000000    0.000000     NaN    0.000000   NaN      NaN
25%      20.125000    0.000000    0.000000     NaN    7.910400   NaN      NaN
50%      28.000000    0.000000    0.000000     NaN   14.454200   NaN      NaN
75%      38.000000    1.000000    0.000000     NaN   31.000000   NaN      NaN
max      80.000000    8.000000    6.000000     NaN  512.329200   NaN      NaN
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
Der häufigste Einschiffungshafen ist: S
Fehlende Werte in 'Embarked' nach dem Füllen: 0
Das Median-Alter beträgt: 28.0
Fehlende Werte in 'Age' nach dem Füllen: 0
Die 'Cabin'-Spalte wurde entfernt.
Die 'Sex'-Spalte wurde in numerische Werte umgewandelt.
Die 'Embarked'-Spalte wurde durch One-Hot Encoding ersetzt.
Die Spalten 'PassengerId', 'Name' und 'Ticket' wurden entfernt.

Final vorbereiteter Datensatz (erste 5 Zeilen):
   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    0  22.0      1      0   7.2500       False       False
1         1       1    1  38.0      1      0  71.2833        True       False
2         1       3    1  26.0      0      0   7.9250       False       False
3         1       1    1  35.0      1      0  53.1000       False       False
4         0       3    0  35.0      0      0   8.0500       False       False

   Embarked_S
0        True
1       False
2        True
3        True
4        True

Datentypen der finalen Spalten:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    int64
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Embarked_C  891 non-null    bool
 8   Embarked_Q  891 non-null    bool
 9   Embarked_S  891 non-null    bool
dtypes: bool(3), float64(2), int64(5)
memory usage: 51.5 KB
Form der Merkmale (X): (891, 9)
Form der Zielvariable (y): (891,)

<ipython-input-6-a504802f625b>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['Embarked'].fillna(embarked_mode, inplace=True)

Größe des Trainingssets: 712 Passagiere
Größe des Testsets: 179 Passagiere
Modell (Logistische Regression) wurde erfolgreich trainiert!
Genauigkeit des Modells auf dem Testset: 81.01%

Klassifikationsbericht:
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179


Konfusionsmatrix:
[[90 15]
 [19 55]]